### PR TITLE
sys-libs/glibc: Revert "Update to glibc 2.33"

### PR DESCRIPTION
**Pull request by sayanchowdhury**
The glibc-2.33-r1 build fails with "no space left on device", so reverting kinvolk/coreos-overlay#1067

Needs to be merged with: https://github.com/kinvolk/portage-stable/pull/182

### CODE REVIEW

**Review by tormath1 — APPROVED** [review]
:rocket:

**Comment by t-lo** [comment]
I think a better path forward would be to just mask ARM64 and AMD64 in the glibc-2.33 ebuild. That way the removal of the (now outdated) 2.29 ebuild is retained.

**Comment by t-lo** [comment]
Alternative PR: https://github.com/kinvolk/coreos-overlay/pull/1081

**Comment by sayanchowdhury** [comment]
Agreed, that would be a much better approach. Thanks! I'll close this PR.

**Pull request closed without merging**
