### PR TITLE
dev-libs/expat: Sync with Gentoo upstream; updates to 2.4.1 

### PR DESCRIPTION
**Pull request by sayanchowdhury**
# dev-libs/expat: Sync with Gentoo upstream; updates to 2.4.1 

## How to use

```bash
emerge-amd64-usr dev-libs/expat
```

## Testing done

Jenkins CI is running, ~http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3171/cldsv/~
http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3189/cldsv/

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
CI Passed. Ready for review.

**Review by jepio — DISMISSED** [review]
Do i understand correctly that usr_ldscript is only used for freebsd and that's why it has been removed? If that's everything then looks good.

**Comment by krnowak** [comment]
Would it be a problem to just move it back to portage-stable? The only differences between upstream and our ebuild are:

1. We do not import usr-ldscript
2. We dropped this part: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/expat/expat-2.4.1.ebuild#n77 (which should be a no-op for us).

**Comment by sayanchowdhury** [comment]
> Would it be a problem to just move it back to portage-stable? The only differences between upstream and our ebuild are:
> 
>     1. We do not import usr-ldscript
> 
>     2. We dropped this part: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/expat/expat-2.4.1.ebuild#n77 (which should be a no-op for us).

CoreOS folks dropped the usr-ldscript inherit, which much information in the commit about why? (Given back then too it seemed that usr-ldscript was mostly non-invasive) https://github.com/coreos/coreos-overlay/commit/b39dd320ca6670ee491ff6d161e2d4189ff11e48

I'm +1 to move to portage-stable, but given we would like to trigger the Alpha release. I could create another PR with the move and appropriate testing, on if there are repercussions. Thoughts?

**Review by krnowak — APPROVED** [review]
Alright, let's do the moving later to avoid blocking the release any further.

**Pull request merged**
