### PR TITLE
Re-enable  FS_ENCRYPTION

### PR DESCRIPTION
**Pull request by ryanm101**
Re-enable FS Encryption per https://github.com/kinvolk/Flatcar/issues/286

### CODE REVIEW

**Comment by jepio** [comment]
Thanks for this, I hope you will now be able to update Flatcar.

**Review by jepio — APPROVED** [review]
Could also be a module but I think its ok to have it builtin.

**Comment by ryanm101** [comment]
I'm trying to build as a module see my build issues thread but having some issues with that. I'm off the rest of this week but will try again next week when i'm back at work.

**Comment by ryanm101** [comment]
Thanks for merging.
I'm trying to build as a module see my build issues thread but having some issues with that. I'm off the rest of this week but will try again next week when i'm back at work.

**Pull request merged**
