### PR TITLE
update sudo to 1.9.5_p2

### PR DESCRIPTION
**Pull request by t-lo**
# update SUDO to 1.9.5_p2

This PR updates sudo to 1.9.5_p2 based on Gentoo's upstream recipe. The previous sudo version (1.8..31) was not removed in order to not break the initial stage(s) of the SDK build.

# How to use

`emerge-amd64-usr sudo`

# Testing done

Ran emerge after updating ebuild. Sudo-1.9.5_p2 was installed.

# Cherry pick to other branches
Cherry-pick to 2605, 2705, 2765 branches.

### CODE REVIEW

**Review by marga-kinvolk — APPROVED** [review]
LGTM

**Review by sayanchowdhury — APPROVED** [review]
LGTM, One nitpick: IMO Changing the commit message title in the second commit to "category/package: Apply Flatcar patches" would help discover the patches easily in the long run.

**Comment by t-lo** [comment]
Reworded the second commit as recommended, thank you both for review and feedback!
Will go ahead and merge now, then cherry-pick to 2605, 2705, 2765 branches.

**Comment by t-lo** [comment]
Merged & cherry-picked; deleting the PR branch now.

**Pull request merged**
