### PR TITLE
app-emulation/runc: remove patches disabling NNP and seccomp

### PR DESCRIPTION
**Pull request by iaguis**
These were included as a workaround for SELinux issues on Flatcar.
However, they also disable NoNewPrivileges and seccomp support, which
reduces security.

Instead, we'll disable SELinux support in the Docker daemon in the next
commit.

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
I've triggered a CI build, will check the results tomorrow.

http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2807/

**Comment by sayanchowdhury** [comment]
CI Passed: CI Passes: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2807/cldsv/

**Review by sayanchowdhury — APPROVED** [review]

**Review by t-lo — APPROVED** [review]
LGTM, thank you.!

**Comment by dongsupark** [comment]
Looks good, thanks!

**Pull request merged**
